global:
    scrape_interval: 15s
    evaluation_interval: 15s

scrape_configs:
    - job_name: "prometheus"
      static_configs:
          - targets: ["localhost:9090"]

    - job_name: "node-exporter"
      static_configs:
          - targets: ["node_exporter:9100"]

    - job_name: "cadvisor"
      static_configs:
          - targets: ["cadvisor:8080"]

    # 监控其他Docker容器（示例）
    # - job_name: 'your-app'
    #   static_configs:
    #     - targets: ['your-app:8000']
